# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sounding the <DANGER/> signal
email: michael.pyne@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The U.S. Navy has undertaken to mandate the use of XML data for all data storage
  and data interchange. In 2019. It also has undertaken to mandate the use of an
  XML compression technology instead of what the rest of the world is already using.
  This document argues against that decision to save
  the Navy and its IT staff some unnecessary heartache and frustration.
  This represents my personal opinion and is not the official position of the Navy,
  U.S. Department of Defense or any other organization or agency.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BlindMansBinary
github_username:  mpyne-navy

# Build settings
markdown: kramdown
theme: jekyll-theme-architect

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
